### ISSUE TITLE
Sintetizar funções de tratamento de sinais

### ISSUE THREAD

**Issue by rodsmade** [rodsmade/Minishell-42sp#12]
- [x] signal
- [x] sigaction
- [x] sigemptyset
- [x] sigaddset
- [x] kill

**Comment by rodsmade** [comment]
REF CABULOSA:
https://github.com/MickeyMighty/MiniShell

**Comment by rodsmade** [comment]
SIGINT (ctrl C) e SIGTERM são caputráveis dentro do pgm com a função signal/sigaction, mas SIGKILL não! https://www.youtube.com/watch?v=83M5-NPDeWs

**Comment by rodsmade** [comment]
`Ctrl + \` = SIGQUIT

**Comment by rodsmade** [comment]
Sobre ctrl D:

não é um signal então não eh com signal/sigaction q vai resolver.

provavelmente a readline tem um comportamento específico pra quando encontra EOF.
Se for testar no bash, o ctrl D chama um exit, então acho que seria tipo isso que teríamos q reproduzir.

EOF parece q eh um NULL:
https://stackoverflow.com/questions/35823864/detecting-ctrl-d-in-c
```line = fgets(l, BUFFSIZE, stdin)
if (line == NULL)
    continue;``` 
    
Essa fgets pelo q sei eh tipo a readline msm...

**Comment by rodsmade** [comment]
pelo que entendi, `sigemptyset ` e `sigaddset ` servem pra criar um grupo (set) de sinais q ficam guardados em uma variável do tipo sigset_t, e deve ser tipo uma lista linkada) . acho que seria útil pra criar um set com SIGINT e SIGQUIT talvez, não sei se terá um uso maior...

**Comment by adrianofaus** [comment]
Signal -> Função que lida com sinais, esta recebe como primeiro argumento um INT que lida com as macros de sinais e uma função de callback como segundo argumento. A função de callback é chamada toda vez que o primeiro argumento é recebido.
Dentre as macros que serão utilizadas a SIGINT será muito relevante na nossa aplicação, pois é ela que lida com sinais iterativos (gerados pelo usuário).

Fonte: https://man7.org/linux/man-pages/man2/signal.2.html

Aqui esta uma lista de caracteres especiais que provocam sinais:

CTRL + C -> É associado a interrupção de todos os processos associados ao terminal.

CTRL + / -> É o mesmo que utilizar a macro SIGQUIT, isto faz com que todos os processos sejam interrompidos. Porém, diferente do CTRL + C o SIGQUIT interrompe os processes provocando um "core dump" no sistema, isto é válido quando o usuário deseja manter arquivos temporários para análise dos processos antes do envio do sinal.

Aqui esta uma referência para sinais de terminação:
https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html

Aqui esta uma referência para mais caracteres que provocam sinais:
https://www.gnu.org/software/libc/manual/html_node/Signal-Characters.html

Aqui esta uma referência para os principais Macros & Sinais
https://www.tutorialspoint.com/c_standard_library/c_function_signal.htm

**Comment by adrianofaus** [comment]
Sigaction -> Pelo o que eu entendi é a mesma coisa que a função signal, porém, sigaction é mais segura, mais atualizada e mais completa do que a Signal, portanto, é mais recomendada.

Diferença entre sigaction e signal: https://stackoverflow.com/questions/231912/what-is-the-difference-between-sigaction-and-signal

**Comment by adrianofaus** [comment]
> SIGINT (ctrl C) e SIGTERM são caputráveis dentro do pgm com a função signal/sigaction, mas SIGKILL não! https://www.youtube.com/watch?v=83M5-NPDeWs

Excelente vídeo, ajudou muito.

**Comment by adrianofaus** [comment]
> `Ctrl + \` = SIGQUIT `Ctrl + C` = SIGINT `Ctrl + D` = não é um sinal, é EOF (https://superuser.com/questions/169051/whats-the-difference-between-c-and-d-for-unix-mac-os-x-terminal)- provavelmente vai ser usado com a readline

Foi o que eu entendi das minhas pesquisas também, teremos que lidar com `Ctrl + D` de maneira separada.

**Comment by adrianofaus** [comment]
> pelo que entendi, `sigemptyset ` e `sigaddset ` servem pra criar um grupo (set) de sinais q ficam guardados em uma variável do tipo sigset_t, e deve ser tipo uma lista linkada) . acho que seria útil pra criar um set com SIGINT e SIGQUIT talvez, não sei se terá um uso maior...

Também não encontrei grande uso para estar funções no momento, mas encontrei um post no stackoverflow onde o cara explica um pouco mais a aplicação destas funções.
https://stackoverflow.com/questions/27227585/what-is-sigaddset-used-for
