### ISSUE TITLE
entender melhor hash map/hash table

### ISSUE THREAD

**Issue by rodsmade** [rodsmade/Minishell-42sp#22]

**Comment by adrianofaus** [comment]
Hastables -> Armazena chave : valor, onde as chaves são colocades em indexes gerados por uma função hash
Buckets -> Estrutura de dados utilizada para lidar com indexes que identicos que guardam chaves diferentes

A complexidade de tempo para Hashtables é constante O(1).

Quando chaves diferentes tendem a ocupar o mesmo index isto é chamado de colisão

-> A escolha da função hash(algoritmo) é de extrema importância, pois é ela que vai determinar qual o nível de colisão da hashtable implementada, sendo que quanto menor a quantidade de colisões, melhor é a performance da hashtable.

-> É importante definir a estrutura de dados para armazenar a hashtable e os itens desta hash, para isso algumas informações são armazenadas:
	-> Uma struct para cada item contendo {key : value}
	-> Uma struct para Hash contendo um double pointer para 	todos os itens, o tamanho da hashtable e quanto elementos a 	hashtable tem.

-> É interessante criar funções que possam:
	-> Procurar valores dentro da hashtable;
	-> Deletar valores;
	-> Inserir valores.

-> Caso uma colisão aconteça é possivel utilizar um método chamado de Separate Chaining, este metodo cria uma cadeia independente de items que tem o mesmo index, neste caso a estrutura de dados utilizadas é a linked lists.

Existe vários tipos de funções hash e vários tipos de tratamentos de colisão, quanto melhor estes metodos melhor será a performance da hashtable.

Source: https://www.journaldev.com/35238/hash-table-in-c-plus-plus

Diferenças entre Hashtable e Hashmap

-> Hashtable, é uma estrutura de dados que armazena informações arbitrárias e não necessáriamente contem um par {key : value, por exemplo o valor dos itens também podem ser seus próprios indexes.
Quando esta destinção não acontece isto é chamado de "set".
Para uma estrutura de dados ser chamada de "hash" é necessária uma função que calcula o index calcula um index da array para armazenar uma {chave : valor}.

-> Hashmap é um conteiner que mapeia chave e valor, sendo que existem diversas implementações para um Hashmap e uma delas pode ser uma hashtable.

No fim uma hashtable  armazena elementos, cada elemento pode ter um par {key : value} distinto, mas caso esta hashtable tenha esta caracteristica então também é chamada de hash map.

https://stackoverflow.com/questions/32274953/difference-between-hashmap-and-hashtable-purely-in-data-structures
