### ISSUE TITLE
Sintetizar funções de terminal

### ISSUE THREAD

**Issue by rodsmade** [rodsmade/Minishell-42sp#23]
Funções pra lidar com terminais (biblioteca: `<termios.h>`)
- [x] isatty
- [x] ttyname
- [x] ttyslot
- [x] ioctl
- [x] getenv
- [x] tcsetattr
- [x] tcgetattr
--------
Funções pra criar uma "GUI" dentro do terminal! (biblioteca `<curses.h>`)
- [x] tgetent
- [x] tgetflag
- [x] tgetnum
- [x] tgetstr
- [x] tgoto
- [x] tputs

**Comment by rodsmade** [comment]
REF CABULOSA:
https://github.com/MickeyMighty/MiniShell

**Comment by rodsmade** [comment]
Conceito de tty:
https://www.youtube.com/watch?v=N1bz1DTD8Io (ótimo e rápido)
https://www.youtube.com/watch?v=4RPtJ9UyHS0 (aulinha de história, mto massa)

**Comment by adrianofaus** [comment]
`isatty` Verifica se o `fd` se refere a um terminal ou não.

`ttyname` Retorna o nome do terminal em que o `fd` esta aberto. Em alguns casos ira retorna `pts` o que significa pseudo-terminal-slave, isto é uma parte do `pty` pseudo-tele-type, criado pelo Kernel para simular um tele-type.
Diferença entre pty e tty: https://www.golinuxcloud.com/difference-between-pty-vs-tty-vs-pts-linux/#:~:text=Stands%20for%20pseudo%20terminal%20slave,or%20ssh%20are%20such%20programs).

`ttyslot` Na versão UnixV6 o gerenciamento de linhas do terminal era controlado pelo programa `init` este programa lia um arquivo que determinava o que deveria ser feito com cada linha do terminal, neste arquivo existia um index que controlava a entrada do usuário atual. Esta função retorna este index. Atualmente, a sintaxe de gerenciamento do terminal é feito de outra maneira e esta função se tornou um legado do Unix.

`ioctl` Input-Output Control function que permite acessar `special device files`, files que conseguem interagir com driver devices do sistema.
Detalhamento da função: https://linuxhint.com/c-ioctl-function-usage/

`getenv` Retorna o caminho de uma variável de ambiente especificada.
https://www.tutorialspoint.com/c_standard_library/c_function_getenv.htm


` tcsetattr`

**Comment by rodsmade** [comment]
> 

sobre a `getenv`, ela retorna o conteúdo da variável de ambiente se ela existe, caso contrário, retorna `NULL`. Acho q vai ser super útil na hora de recriar o pipex e de manipular as variáveis de ambiente

**Comment by rodsmade** [comment]
e mano não consigo enxergar exatamente onde vamos usar essas funções de terminal, controle de I/O... parece algo mais avançado que não é necessário pra fazer um mini-shell. 

Descobri isso aqui que dá pra fazer com a curses.h:
https://www.youtube.com/watch?v=K8dCh3ZMLN8
Tem cara de ser coisa opcional mesmo, se der tempo, etc.

**Comment by adrianofaus** [comment]
> 

Concordo com isso, também não consegui enxergar.

**Comment by adrianofaus** [comment]
> e mano não consigo enxergar exatamente onde vamos usar essas funções de terminal, controle de I/O... parece algo mais avançado que não é necessário pra fazer um mini-shell.
> 
> Descobri isso aqui que dá pra fazer com a curses.h: https://www.youtube.com/watch?v=K8dCh3ZMLN8 Tem cara de ser coisa opcional mesmo, se der tempo, etc.

Concordo com isso, também não consegui enxergar onde usaremos.
