### ISSUE TITLE
built-in: pwd

### ISSUE THREAD

**Issue by rodsmade** [rodsmade/Minishell-42sp#6]
implement "pwd" built-in with no options

**Comment by adrianofaus** [comment]
Eu encontrei fontes para chegar a função que que estamos utilizando:

Primeiro eu busquei funções permitidas que tinham relação com diretórios e encontrei estas:

- chdir
>  Esta função se move para o diretório especificado como argumento (vai ajudar no CD, mas não é a hora).
Source: https://man7.org/linux/man-pages/man2/chdir.2.html

- stat, lstat, fstat
> Esse grupo de funções buscam informações sobre um determinado file passado como argumento (um diretório é um file também) e guardam estas informações dentro de um buffer passado também com argumento. Este buffer, estará em um no formato `struct stat`.

- opendir, readdir, closedir
